
//
//	This code is autogenerated.  Please do not modify by hand.
//

using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;

public class OpenSceneMenu
{

[MenuItem("OpenScene/BootstrapScene",false,0)]
static void OpenScene0()
{
	EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
	EditorSceneManager.OpenScene("Assets/MSPlayground/Core/Bootstrapper/BootstrapScene.unity", OpenSceneMode.Single);
}

[MenuItem("OpenScene/BootstrapScene Additive",false,0)]
static void OpenScene0_Additive()
{
	EditorSceneManager.OpenScene("Assets/MSPlayground/Core/Bootstrapper/BootstrapScene.unity", OpenSceneMode.Additive);
}


[MenuItem("OpenScene/Hub",false,1)]
static void OpenScene1()
{
	EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
	EditorSceneManager.OpenScene("Assets/MSPlayground/Hub/Scenes/Hub.unity", OpenSceneMode.Single);
}

[MenuItem("OpenScene/Hub Additive",false,1)]
static void OpenScene1_Additive()
{
	EditorSceneManager.OpenScene("Assets/MSPlayground/Hub/Scenes/Hub.unity", OpenSceneMode.Additive);
}


[MenuItem("OpenScene/Turbines",false,2)]
static void OpenScene2()
{
	EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
	EditorSceneManager.OpenScene("Assets/MSPlayground/Turbines/Scenes/Turbines.unity", OpenSceneMode.Single);
}

[MenuItem("OpenScene/Turbines Additive",false,2)]
static void OpenScene2_Additive()
{
	EditorSceneManager.OpenScene("Assets/MSPlayground/Turbines/Scenes/Turbines.unity", OpenSceneMode.Additive);
}


[MenuItem("OpenScene/TurbineVREnvironment",false,3)]
static void OpenScene3()
{
	EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
	EditorSceneManager.OpenScene("Assets/MSPlayground/Turbines/Scenes/TurbineVREnvironment.unity", OpenSceneMode.Single);
}

[MenuItem("OpenScene/TurbineVREnvironment Additive",false,3)]
static void OpenScene3_Additive()
{
	EditorSceneManager.OpenScene("Assets/MSPlayground/Turbines/Scenes/TurbineVREnvironment.unity", OpenSceneMode.Additive);
}


[MenuItem("OpenScene/HubVREnvironment",false,4)]
static void OpenScene4()
{
	EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
	EditorSceneManager.OpenScene("Assets/MSPlayground/Hub/Scenes/HubVREnvironment.unity", OpenSceneMode.Single);
}

[MenuItem("OpenScene/HubVREnvironment Additive",false,4)]
static void OpenScene4_Additive()
{
	EditorSceneManager.OpenScene("Assets/MSPlayground/Hub/Scenes/HubVREnvironment.unity", OpenSceneMode.Additive);
}


}
